name: leelando_video_example
description: 展示 leelando_video 多内核播放器的功能和常见影视播放场景。
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  leelando_video: ^1.0.1
  leelando_video_all: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/demo_tone.mp4
